apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
    label-one: "value-one"
  name: computeforwardingrule-sample-global-with-target-http-proxy
spec:
  description: "A global forwarding rule"
  target:
    targetHTTPProxyRef:
      name: computeforwardingrule-dep-global-with-target-http-proxy
  portRange: "80"
  ipProtocol: "TCP"
  ipVersion: "IPV4"
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPProxy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeforwardingrule-dep-global-with-target-http-proxy
spec:
  urlMapRef:
    name: computeforwardingrule-dep-global-with-target-http-proxy
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeforwardingrule-dep-global-with-target-http-proxy
spec:
  defaultService:
    backendServiceRef:
      name: computebackendservice-sample-externalloadbalancing
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-sample-externalloadbalancing
spec:
  description: External backend service with cookie-based session affinity.
  portName: cookie-cloud
  timeoutSec: 30
  healthChecks:
  - healthCheckRef:
      name: computeinstancegroupmanager-dep-zonal
  loadBalancingScheme: EXTERNAL
  location: global
  protocol: HTTP
  affinityCookieTtlSec: 360
  connectionDrainingTimeoutSec: 60
  securityPolicyRef:
    name: computebackendservice-dep-externalloadbalancing
  sessionAffinity: GENERATED_COOKIE
  customRequestHeaders:
    - "Trailer: custom-trailer"
  logConfig:
    enable: false
  backend:
  - balancingMode: RATE
    capacityScaler: 0.9
    description: An instance group serving this backend with 90% of its capacity, as calculated by requests per second.
    maxRate: 10000
    group:
      instanceGroupRef:
        name: computeinstancegroupmanager-sample-zonal
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroup
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-sample-zonal
spec:
  instances:
  - name: computeinstancegroup-dep1
  - name: computeinstancegroup-dep2
  namedPort:
  - name: http
    port: 80
  zone: us-west1-a
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroup-dep1
spec:
  zone: us-west1-a
  instanceTemplateRef:
    name: computeinstancegroupmanager-dep-zonal
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroup-dep2
spec:
  zone: us-west1-a
  instanceTemplateRef:
    name: computeinstancegroupmanager-dep-zonal
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-dep-zonal
spec:
  httpHealthCheck:
    port: 80
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-dep-zonal
spec:
  machineType: n1-standard-1
  metadataStartupScript: apt-get install apache2 -y
  disk:
  - sourceImageRef:
      external: debian-cloud/debian-11
    boot: true
  - deviceName: disk-a
    sourceImageRef:
      external: debian-cloud/debian-11
    autoDelete: true
    boot: false
  networkInterface:
  - networkRef:
      name: computebackendservice-dep-externalloadbalancing
    subnetworkRef:
      name: computebackendservice-dep-externalloadbalancing
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  rule:
  - action: deny(403)
    priority: 2147483647
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - "*"
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  networkRef:
    name: computebackendservice-dep-externalloadbalancing
