apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: false
