apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroup
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-sample-zonal
spec:
  instances:
  - name: computeinstancegroup-dep1
  - name: computeinstancegroup-dep2
  namedPort:
  - name: http
    port: 80
  zone: us-west1-a
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroup-dep1
spec:
  zone: us-west1-a
  instanceTemplateRef:
    name: computeinstancegroupmanager-dep-zonal
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroup-dep2
spec:
  zone: us-west1-a
  instanceTemplateRef:
    name: computeinstancegroupmanager-dep-zonal
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-dep-zonal
spec:
  httpHealthCheck:
    port: 80
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computeinstancegroupmanager-dep-zonal
spec:
  machineType: n1-standard-1
  metadataStartupScript: apt-get install apache2 -y
  disk:
  - sourceImageRef:
      external: debian-cloud/debian-11
    boot: true
  - deviceName: disk-a
    sourceImageRef:
      external: debian-cloud/debian-11
    autoDelete: true
    boot: false
  networkInterface:
  - networkRef:
      name: computebackendservice-dep-externalloadbalancing
    subnetworkRef:
      name: computebackendservice-dep-externalloadbalancing
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: computebackendservice-dep-externalloadbalancing
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  networkRef:
    name: computebackendservice-dep-externalloadbalancing
