apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "heewonk-bunker"
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    environment: "staging"
    owner: "heewonk"
    team: "pso-japac"
  name: heewonk-bunker-storage-demo-2
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
  versioning:
    enabled: true
  cors:
    - origin: ["http://heewonk-bunker.appspot.com"]
      responseHeader: ["Content-Type"]
      method: ["GET", "HEAD", "DELETE"]
      maxAgeSeconds: 3600
  uniformBucketLevelAccess: true
