apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Release.Name }}-instance-1"
spec:
  zone: {{ .Values.instance.zone }}
