apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Values.project.id }}-{{ .Release.Name }}-{{ .Values.env.name }}"
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: {{ .Values.bucket.lifecycle.age }}
  versioning:
    enabled: {{ .Values.bucket.versioning }}
  uniformBucketLevelAccess: {{ .Values.bucket.uniform }}
