apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroupManager
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Values.app.name }}-instance-group"
spec:
  projectRef:
    external: "projects/{{ .Values.project.id }}"
  location: {{ .Values.instance.region }}
  namedPorts:
  - name: http
    port: 8080
  autoHealingPolicies:
    - healthCheckRef:
        name: "{{ .Values.app.name }}-healthcheck"
      initialDelaySec: 300
  targetSize: 10
  instanceTemplateRef:
    name: "{{ .Values.app.name }}-instance-template-{{ .Values.version }}"
  updatePolicy:
    instanceRedistributionType: PROACTIVE
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Values.app.name }}-healthcheck"
spec:
  checkIntervalSec: 30
  httpHealthCheck:
    port: 8080
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Values.app.name }}-instance-template-{{ .Values.version }}"
spec:
  tags:
  - http-server
  - https-server
  region: {{ .Values.instance.region }}
  machineType: {{ .Values.instance.machineType }}
  metadataStartupScript: "#! /bin/bash\nnohup java -jar /home/reolee/spring-petclinic/target/*.jar &"
  disk:
  - sourceImageRef:
      external: {{ .Values.instance.image }}
    boot: true
  networkInterface:
  - networkRef:
      external: default
    subnetworkProject: {{ .Values.project.id }}
    subnetworkRef:
      external: default
