apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.id }}
    cnrm.cloud.google.com/force-destroy: "{{ .Values.destroy }}"
  labels:
    environment: {{ .Values.env.name }}
    owner: {{ .Values.owner }}
    team: {{ .Values.team }}
  name: "{{ .Values.project.id }}-{{ .Release.Name }}-instance-template"
spec:
  region: {{ .Values.instance.region }}
  machineType: {{ .Values.instance.machineType }}
  metadataStartupScript: apt-get install apache2 -y
  disk:
  - sourceImageRef:
      external: {{ .Values.instance.image }}
    boot: true
  networkInterface:
  - networkRef:
      external: {{ .Values.instance.vpc | default }}
    subnetworkProject: {{ .Values.project.id }}
    subnetworkRef:
      external: {{ .Values.instance.subnet | default }}
