project:
  id: meta-sanctum-341404
destroy: true
env:
  name: dev
owner: reolee
team: pso-japac
bucket:
  lifecycle:
    age: 7
  versioning: true
  uniform: true
instance:
  machineType: n1-standard-1
  zone: us-central1-a
  region: us-central1
  image: debian-cloud/debian-11
version: 1
